// THE WORDS OF EVERY NOTIFICATION, IN ONE FILE (2026-10-09).
//
// Edit the words here, then run `node scripts/build-notifications-preview.mjs`
// to see every one of them rendered in .claude-notes/notifications-preview.html.
//
// WHAT READS THIS FILE
//   phone push      lib/dash/pushRules.js (MLB, NFL, NHL, BUCKETS producers),
//                   lib/nhl/goalFeed.js pushText, app/api/dash/push/tick
//                   (bundles), app/api/dash/push/subscribe (welcome)
//   in-app toast    components/MiniWire.js, components/nfl/NflWire.js
//   bell / prompt   components/MiniWire.js, lib/notify.js (iPhone hint)
//   LiveWire rows   components/LiveWire.js
//   BUCKETS post    lib/nba/moments.js
//   settings panel  lib/dash/alerts.js (labels + one-line details)
// The Discord pen-door words live in the bot repo (bots/copy_pendoor.py).
// FRANCHISE push words (lib/dash/franchise.js) are owned by the FRANCHISE
// workflow and are NOT moved here; they are listed in CATALOG as "owned elsewhere".
//
// THE RULES THESE WORDS FOLLOW (tests: scripts/check-notification-copy.mjs)
//   * Title <= 26 characters, body <= 48, ONE line, no sentences. The news is
//     FIRST: the stat / status / count sits inside the first 30 characters, so a
//     phone's "..." never eats it. Innings are scoreboard shorthand (▲1 top, ▼7
//     bottom), periods P2, quarters Q3. A score is "TB 4, NYY 2": LEADER FIRST.
//   * The player's name appears ONCE, in the title (full name when it fits in 26
//     characters, else last name). The body is the situation. No "DASH" anywhere.
//   * Status words are exactly CALLED / ON THE BOARD / NOT ON THE BOARD
//     (STATUS_WORD in lib/callStatus.js). Nothing here decides which one.
//   * No links, no hashtags, no probability words, no developer words, no
//     "bot 7th" ("Bottom 7th"), no raw feed words ("Delayed: RAIN" -> "Rain delay").
//   * In-game events carry the live score: "▼7 · NYY 3, TB 2".
//   * Counts go through plural(): "1 pick", "2 picks", never "1 names".
//   * The status word (CALLED) leads the body when there is room. The existing
//     CALLED goal push keeps its words character for character.
//   * MOONSHOT's CALLED alert (lib/dash/homerFeed.js postText, X and Discord) is
//     NOT in this file and is not to be touched: a snapshot test guards it.
//
// <<CATALOG (generated by scripts/build-notifications-preview.mjs --header; do not edit by hand)
// key (variant)                      kind     trigger  <- producer
//   boardup                            push     The first lineup with a pick in it is posted (once a day).  <- lib/dash/pushRules.js pregameEventsFrom
//   boardup (one pick)                 push     Same, one pick.  <- lib/dash/pushRules.js pregameEventsFrom
//   lastcall                           push     A game with your picks in the posted lineup starts within 30 minutes (once per start time).  <- lib/dash/pushRules.js pregameEventsFrom
//   lastcall (one pick)                push     Same, one pick.  <- lib/dash/pushRules.js pregameEventsFrom
//   scratched                          push     A board pick is not in a posted lineup.  <- lib/dash/pushRules.js pregameEventsFrom
//   dropout                            push     A followed man (not on the board) is left out of a posted lineup.  <- lib/dash/pushRules.js mlbEventsFrom
//   gameoff (rain delay, lineup posted) push     A game with your picks is delayed.  <- lib/dash/pushRules.js pregameEventsFrom
//   gameoff (delay, no lineup yet)     push     Same, lineups not posted.  <- lib/dash/pushRules.js pregameEventsFrom
//   gameoff (postponed)                push     Postponed.  <- lib/dash/pushRules.js pregameEventsFrom
//   homer (CALLED)                     push     A followed hitter goes deep; he was CALLED.  <- lib/dash/pushRules.js mlbEventsFrom
//   homer (second homer)               push     His second homer tonight.  <- lib/dash/pushRules.js mlbEventsFrom
//   finalline                          push     His night is over and he had an at-bat.  <- lib/dash/pushRules.js mlbEventsFrom
//   nfltd (rushing or receiving, CALLED) push     A followed player scores (rushing or receiving).  <- lib/dash/pushRules.js nflEventsFrom
//   nfltd (passing)                    push     A followed quarterback throws a touchdown.  <- lib/dash/pushRules.js nflEventsFrom
//   nflkick                            push     A game with your players kicks off.  <- lib/dash/pushRules.js nflEventsFrom
//   nhlgoal (CALLED (existing words, kept character for character)) push     A followed skater scores; he was CALLED.  <- lib/nhl/goalFeed.js pushText
//   nhlgoal (ON THE BOARD)             push     Same, on the board.  <- lib/nhl/goalFeed.js pushText
//   nhlgoal (NOT ON THE BOARD)         push     Same, off the board.  <- lib/nhl/goalFeed.js pushText
//   bundle                             system   Several events for one device in one minute.  <- app/api/dash/push/tick/route.js bundle
//   bundle (seven)                     system   Seven at once.  <- app/api/dash/push/tick/route.js bundle
//   welcome                            system   A new device turns alerts on.  <- app/api/dash/push/subscribe/route.js
//   ondeck                             push     [cut] CUT. A followed hitter is on deck in a live game.  <- lib/dash/pushRules.js mlbEventsFrom
//   slam                               push     A pick is up with the bases loaded (this replaced ON DECK).  <- lib/dash/pushRules.js mlbEventsFrom
//   hrr                                push     Hits + runs + RBI reaches two (a cash event).  <- lib/dash/pushRules.js mlbEventsFrom
//   bigbases                           push     Four or more total bases (a cash event).  <- lib/dash/pushRules.js mlbEventsFrom
//   multihit                           push     Two hits, and again at three (a cash event).  <- lib/dash/pushRules.js mlbEventsFrom
//   slate                              push     [cut] CUT. Anyone goes deep.  <- lib/dash/pushRules.js mlbEventsFrom
//   nflred                             push     [cut] CUT. His offence is inside the 20.  <- lib/dash/pushRules.js nflEventsFrom
//   nba30                              push     [cut] CUT (BUCKETS off). A followed player reaches 30.  <- lib/dash/pushRules.js nbaEventsFrom
//   bucketsPost                        post     A 30-point night (X / Discord, BUCKETS off).  <- lib/nba/moments.js momentText
//   bell-armed                         bell     The bell is turned on and the browser allows it.  <- components/MiniWire.js toggleNotif
//   bell-ios                           bell     Bell tapped in Safari on an iPhone that has not installed the site.  <- lib/notify.js installHint
//   bell-signin                        bell     Bell turned on while signed out.  <- components/MiniWire.js toggleNotif
//   toast-hr                           toast    A pick or watchlist man homers (page open).  <- components/MiniWire.js
//   toast-up                           toast    A pick is at the plate (page open).  <- components/MiniWire.js
//   toast-k                            toast    A pick goes 0-for with a second strikeout.  <- components/MiniWire.js
//   toast-scr                          toast    A pick is not in a posted lineup (page open).  <- components/MiniWire.js
//   toast-nfltd                        toast    A followed player scores (page open).  <- components/nfl/NflWire.js
//   lw-pair                            livewire Both legs of a pair homered.  <- components/LiveWire.js
//   lw-stopped                         livewire A game is delayed, suspended or postponed.  <- components/LiveWire.js
//   lw-needs                           livewire A live pick still needs something in the 7th or later.  <- components/LiveWire.js
//   lw-bullpen                         livewire A starter is at 85+ pitches.  <- components/LiveWire.js
//   lw-hr2                             livewire A hitter has 2+ homers tonight.  <- components/LiveWire.js
// CATALOG>>

import { STATUS_WORD } from '../callStatus'

// ── small shared words ──────────────────────────────────────────────────────
const num = (v) => (Number.isFinite(Number(v)) ? Number(v) : 0)
const txt = (v) => String(v == null ? '' : v).trim()
const ord = (k) => `${k}${[11, 12, 13].includes(k % 100) ? 'th' : ({ 1: 'st', 2: 'nd', 3: 'rd' }[k % 10] || 'th')}`
const cp = (s) => [...String(s)].length          // length in characters, emoji counted once
const SEP = ' · '

export const EMOJI = { mlb: '⚾', nfl: '\u{1F3C8}', nhl: '\u{1F6A8}', nba: '\u{1F3C0}' }
export const LIMITS = { title: 26, body: 48, keyBy: 30 }

/** "1 pick" / "2 picks" / "0 picks". Pass `many` for an irregular plural. */
export const plural = (n, one, many) => `${n} ${n === 1 ? one : (many || `${one}s`)}`
/** "is" / "are" for a count. */
export const isAre = (n) => (n === 1 ? 'is' : 'are')

/** "A", "A and B", "A, B and C", "A, B +2" -- names are never repeated. */
export function joinNames(names, max = 3) {
  const u = [...new Set((names || []).map(txt).filter(Boolean))]
  if (u.length <= 1) return u[0] || ''
  const shown = u.slice(0, max)
  const more = u.length - shown.length
  if (more > 0) return `${shown.join(', ')} +${more}`
  return `${shown.slice(0, -1).join(', ')} and ${shown[shown.length - 1]}`
}

/** Last name ("Jr." / "III" dropped): the form a 26-character title falls back to. */
export function lastNameOf(full) {
  const parts = txt(full).split(/\s+/).filter(Boolean)
  if (!parts.length) return 'Your guy'
  if (parts.length === 1) return parts[0]
  const tail = parts.slice(1).filter((p) => !/^(jr\.?|sr\.?|i{2,3}|iv|v)$/i.test(p))
  return (tail.length ? tail : parts.slice(1)).join(' ')
}

const clip = (s, n) => (cp(s) <= n ? s : `${[...s].slice(0, n - 1).join('').trimEnd()}…`)

/** "⚾ Full Name suffix" if it fits in the title limit, else with the last name. */
export function titleWith(emoji, name, suffix = '', max = LIMITS.title) {
  const pre = emoji ? `${emoji} ` : ''
  const tail = suffix ? ` ${suffix}` : ''
  const full = `${pre}${name}${tail}`
  if (cp(full) <= max) return full
  return clip(`${pre}${lastNameOf(name)}${tail}`, max)
}
/** A title with no name in it. */
export const titleOnly = (emoji, words, max = LIMITS.title) => clip(`${emoji ? `${emoji} ` : ''}${words}`, max)

/** One line of facts: parts joined with " · ", trailing parts dropped (never clipped mid-fact) until it fits. */
export function fitBody(parts, max = LIMITS.body) {
  const p = parts.map(txt).filter(Boolean)
  while (p.length > 1 && cp(p.join(SEP)) > max) p.pop()
  return clip(p.join(SEP), max)
}

/** Scoreboard shorthand: ▲6 = top of the 6th, ▼7 = bottom of the 7th. */
export function inningShort(half, inning) {
  const n = num(inning)
  if (!n) return ''
  return `${/^top|^middle/i.test(txt(half)) ? '▲' : '▼'}${n}`
}
/** The long form, where there is room (Discord, on-page toasts): "Top 7th" / "Bottom 7th". */
export function inningText(half, inning) {
  const n = num(inning)
  if (!n) return ''
  return `${/^top|^middle/i.test(txt(half)) ? 'Top' : 'Bottom'} ${ord(n)}`
}

/** "NYY 3, TB 2": LEADER FIRST, everywhere. "Tied 3-3". '' when either side is unknown. */
export function scoreText({ away, home, awayScore, homeScore } = {}) {
  const a = txt(away); const h = txt(home)
  if (!a || !h || awayScore == null || homeScore == null) return ''
  const as = num(awayScore); const hs = num(homeScore)
  if (as === hs) return `Tied ${as}-${hs}`
  return as > hs ? `${a} ${as}, ${h} ${hs}` : `${h} ${hs}, ${a} ${as}`
}
/** "▼7" + "NYY 3, TB 2" as two parts, in glance order. */
export const gameParts = (g) => [inningShort(g?.half, g?.inning), scoreText(g)].filter(Boolean)

/** "7:05 PM ET" from epoch ms. */
export function timeET(ms) {
  try {
    const s = new Intl.DateTimeFormat('en-US', { timeZone: 'America/New_York', hour: 'numeric', minute: '2-digit' }).format(new Date(ms))
    return `${s} ET`
  } catch { return '' }
}

// ── hitting words ───────────────────────────────────────────────────────────
/** "2-for-3" */
export const hitLine = (l) => `${num(l?.h)}-for-${num(l?.ab)}`
const BAR_WORD = { HR: 'HR', XBH: 'extra bases', 'multi-hit': 'multi-hit', HRR: 'HRR', hit: 'hit', '2TB': '2 bases' }
const barWords = (bars) => (bars || []).map((b) => BAR_WORD[b] || b).join(', ')
const statusBy = (status) => (status === 'called' ? STATUS_WORD.called : status === 'board' ? STATUS_WORD.board : status === 'off' ? STATUS_WORD.off : '')

// ── PHONE PUSH: MLB ─────────────────────────────────────────────────────────
// Every function returns { title, body, short, group }. `short` is the LAST name
// or a count (a bundle's body is cut at 48 characters); `group` is the verb a
// bundle's count attaches to.

export const mlb = {
  /** boardup -- the lineup is posted and at least one pick is in it. */
  boardSet: ({ count, time }) => ({
    title: titleOnly('\u{1F4CB}', 'Your board is set'),
    body: fitBody([plural(count, 'pick'), `first pitch ${time}`]),
    short: plural(count, 'pick'), group: 'boards are set',
  }),
  /** lastcall -- one per start time; counts only picks in the posted lineup. */
  firstPitchSoon: ({ mins, count }) => ({
    title: titleOnly('⏰', `First pitch in ${mins} min`),
    body: fitBody([`${count} of your ${count === 1 ? 'picks is' : 'picks are'} in the lineup`]),
    short: plural(count, 'pick'), group: 'games start soon',
  }),
  /** scratched -- a board pick, lineup posted, he is not in it. */
  scratch: ({ name }) => ({
    title: titleWith('⚠️', name, 'is out'),
    body: "Not in tonight's lineup",
    short: lastNameOf(name), group: 'were scratched',
  }),
  /** dropout -- a followed man (not on the board) left out of a posted card. */
  lineupChange: ({ name }) => ({
    title: titleWith('\u{1F4E4}', name, 'is out'),
    body: "Lineup change: not in tonight's lineup",
    short: `${lastNameOf(name)} (out)`, group: 'dropped from the lineup',
  }),
  /** gameoff -- delay / suspension / postponement. `lineupPosted` decides what we may say about picks. */
  gameOff: ({ kind, reason, away, home, count, lineupPosted }) => {
    const head = gameOffHeadline(kind, reason)
    const parts = [`${away} at ${home}`]
    if (kind === 'postponed') { if (count > 0) parts.push(`${count} of your picks`) }
    else if (!lineupPosted) parts.push('lineups not posted')
    else if (count > 0) parts.push(`${count} of your picks`)
    return { title: titleOnly('⚠️', head), body: fitBody(parts), short: `${away}-${home}`, group: 'games are off' }
  },
  /** homer -- a followed hitter goes deep. `called` puts the status word first. */
  homer: ({ name, n, line, game, called }) => ({
    title: titleWith('\u{1F4A5}', name, n > 1 ? `homer #${n}` : 'goes deep'),
    body: fitBody([called ? STATUS_WORD.called : '', 'HR', hitLine(line), ...gameParts(game)]),
    short: n > 1 ? `${lastNameOf(name)} (${n})` : lastNameOf(name), group: 'went deep',
  }),
  /** finalline -- his night is over (the final recap). */
  finalLine: ({ name, line, bars, game }) => {
    const sc = scoreText(game)
    return {
      title: titleWith('\u{1F3C1}', name, hitLine(line)),
      body: fitBody([bars?.length ? barWords(bars) : 'Nothing cleared', sc ? `${sc} final` : '']),
      short: lastNameOf(name), group: 'are done for the night',
    }
  },
  /** slam -- a pick is up with the bases loaded. This replaced ON DECK (2026-10-09). */
  basesLoaded: ({ name, outs, game }) => ({
    title: titleWith('\u{1F9E8}', name, 'up, bases loaded'),
    body: fitBody([plural(outs, 'out'), ...gameParts(game)]),
    short: `${lastNameOf(name)} (loaded)`, group: 'are up with the bases loaded',
  }),
  /** hrr -- hits + runs + RBI reached two. Zero parts are left out. */
  hrrCleared: ({ name, line, game }) => ({
    title: titleWith('✅', name, 'cleared HRR'),
    body: fitBody([[num(line?.h) ? `${num(line.h)} H` : '', num(line?.r) ? `${num(line.r)} R` : '', num(line?.rbi) ? `${num(line.rbi)} RBI` : ''].filter(Boolean).join(', '), ...gameParts(game)]),
    short: lastNameOf(name), group: 'cleared HRR',
  }),
  /** bigbases -- four or more total bases. */
  bigBases: ({ name, tb, line, game }) => ({
    title: titleWith('\u{1F4AA}', name, `${tb} bases`),
    body: fitBody([hitLine(line), ...gameParts(game)]),
    short: `${lastNameOf(name)} (${tb})`, group: 'are piling bases',
  }),
  /** multihit -- the hit bar: two hits, and again at three. */
  multiHit: ({ name, h, ab, game }) => ({
    title: titleWith('\u{1F3AF}', name, `${h} hits`),
    body: fitBody([`${h}-for-${ab}`, ...gameParts(game)]),
    short: `${lastNameOf(name)} ${h}-${ab}`, group: 'have multi-hit nights',
  }),
  // ── cut categories (kept reachable behind PUSH_CUT_CATEGORIES=on) ──
  lineup: ({ name, slot }) => ({ title: titleWith('\u{1F4CB}', name, `bats ${slot || '?'}`), body: "In tonight's lineup", short: `${lastNameOf(name)} ${slot || ''}`.trim(), group: 'are in the lineup' }),
  callup: ({ name, slot }) => ({ title: titleWith('\u{1F195}', name, 'is in'), body: fitBody(['First posted lineup we have seen', `bats ${slot || '?'}`]), short: `${lastNameOf(name)} (new)`, group: 'are new to the lineup' }),
  underway: ({ names }) => ({ title: titleOnly('▶️', 'Underway'), body: fitBody([names.length > 2 ? `${names.length} of your players` : joinNames(names.map(lastNameOf)), 'first pitch']), short: joinNames(names.map(lastNameOf)), group: 'games started' }),
  extraBases: ({ name, triple, line, game }) => ({ title: titleWith('⚡', name, triple ? 'triples' : 'doubles'), body: fitBody([hitLine(line), ...gameParts(game)]), short: lastNameOf(name), group: 'got extra bases' }),
  coldStart: ({ name, ab, k, game }) => ({ title: titleWith('\u{1F976}', name, `is 0-for-${ab}`), body: fitBody([plural(k, 'strikeout'), ...gameParts(game)]), short: `${lastNameOf(name)} 0-${ab}`, group: 'are going cold' }),
  onDeck: ({ name, outs, on, loaded, game }) => ({ title: titleWith('⚾', name, 'on deck'), body: fitBody([`${plural(outs, 'out')}${loaded ? ', loaded' : on ? `, ${on} on` : ''}`, ...gameParts(game)]), short: `${lastNameOf(name)} on deck`, group: 'are coming up' }),
  clutch: ({ name, on, outs, game }) => ({ title: titleWith('\u{1F525}', name, `up, ${on} on`), body: fitBody([plural(outs, 'out'), ...gameParts(game)]), short: `${lastNameOf(name)} (${on} on)`, group: 'are in a spot' }),
  scoreSwing: ({ whose, game, outs }) => ({ title: titleOnly('\u{1F501}', scoreText(game) || 'Close game'), body: fitBody([inningShort(game.half, game.inning), outs != null ? plural(outs, 'out') : '', 'your pick is in it']), short: whose, group: 'are in a close one' }),
  gameFinal: ({ whose, game, names }) => ({ title: titleOnly('\u{1F3C1}', scoreText(game) ? `${scoreText(game)} F` : 'Final'), body: fitBody([plural(names.length, 'pick'), 'of yours played']), short: whose, group: 'games finished' }),
  /** slate -- ANY homer on the slate; `status` is a STATUS_WORD value. */
  slateHomer: ({ name, n, status, rank, line }) => ({
    title: titleWith('\u{1F4A5}', name, n > 1 ? `homer #${n}` : 'goes deep'),
    body: fitBody([status === STATUS_WORD.off ? status : status ? `${status} #${rank}` : '', hitLine(line)]),
    short: rank ? `${lastNameOf(name)} (#${rank})` : lastNameOf(name), group: 'went deep',
  }),
}

/** Delay / suspension / postponement headline from the league's own words. */
export function gameOffHeadline(kind, reasonRaw) {
  const m = txt(reasonRaw).match(/(?:[:(]\s*)([A-Za-z][A-Za-z ]*?)\)?\s*$/)
  let reason = m ? m[1].trim() : ''
  if (/^(start|game)$/i.test(reason)) reason = ''
  const cap = reason ? reason.charAt(0).toUpperCase() + reason.slice(1).toLowerCase() : ''
  if (kind === 'postponed') return `Postponed${cap ? ` (${cap.toLowerCase()})` : ''}`
  if (kind === 'suspended') return `Suspended${cap ? ` (${cap.toLowerCase()})` : ''}`
  return cap ? `${cap} delay` : 'Delay'
}

// ── PHONE PUSH: TUDDY ───────────────────────────────────────────────────────
const nflQuarter = (p) => { const n = num(p); return n > 4 ? 'OT' : n >= 1 ? `Q${n}` : '' }
export const nflGameParts = (g) => [nflQuarter(g?.period), scoreText({ away: g?.away, home: g?.home, awayScore: g?.away_score, homeScore: g?.home_score })].filter(Boolean)
const tdsOf = (l) => num(l?.receiving_tds) + num(l?.rushing_tds)

export const nfl = {
  /** nfltd -- a followed player scores (rushing or receiving). */
  touchdown: ({ name, tds, line, game, called }) => ({
    title: titleWith('\u{1F3C8}', name, 'scores'),
    body: fitBody([called ? STATUS_WORD.called : '', tds > 1 ? `TD ${tds}` : 'TD', ...nflGameParts(game), `${num(line?.receptions)} rec, ${num(line?.receiving_yards)} yds`]),
    short: tds > 1 ? `${lastNameOf(name)} (${tds})` : lastNameOf(name), group: 'scored',
  }),
  /** nfltd -- a followed quarterback throws one. Counted from passing_tds, said as a throw. */
  passingTouchdown: ({ name, tds, line, game }) => ({
    title: titleWith('\u{1F3C8}', name, 'throws a TD'),
    body: fitBody([tds > 1 ? `TD pass ${tds}` : 'TD pass', ...nflGameParts(game), `${num(line?.passing_yards)} yds`]),
    short: tds > 1 ? `${lastNameOf(name)} (${tds})` : lastNameOf(name), group: 'threw touchdowns',
  }),
  kickoff: ({ away, home, count }) => ({
    title: titleOnly('\u{1F3C8}', 'Kickoff'),
    body: fitBody([`${away} at ${home}`, `${count} of your players`]),
    short: `${away}@${home}`, group: 'games kicked off',
  }),
  // ── cut categories ──
  redZone: ({ team, names, down, clock, game }) => ({ title: titleOnly('\u{1F6A9}', `${team} in the red zone`), body: fitBody([...nflGameParts(game), down, clock, joinNames(names.map(lastNameOf), 2)]), short: `${team} red zone`, group: 'are in the red zone' }),
  boardRedZone: ({ team, men, down, clock, game }) => ({ title: titleOnly('\u{1F6A9}', `${team} in the red zone`), body: [...nflGameParts(game), men.map((m) => `${lastNameOf(m.name)} #${m.rank}${m.called ? ' CALLED' : ''}`).join(', '), down, clock].filter(Boolean).join(SEP), short: `${team} red zone`, group: 'TUDDY board men are in the red zone' }), // the room's text (Discord), not a phone's: no length cap
  oneScore: ({ away, home, game, clock }) => ({ title: titleOnly('\u{1F525}', 'One-score game'), body: fitBody([...nflGameParts(game), clock, `${away}-${home}`]), short: `${away}-${home}`, group: 'games are close' }),
  bigDay: ({ name, yds, kind, line, game }) => ({ title: titleWith('\u{1F4C8}', name, `${yds} ${kind} yds`), body: fitBody([`${tdsOf(line)} TD`, ...nflGameParts(game)]), short: `${lastNameOf(name)} ${yds}`, group: 'are having big days' }),
}

// ── PHONE PUSH: LAMP ────────────────────────────────────────────────────────
const nhlStrength = (s) => ({ 'PP goal': 'PP', 'SH goal': 'SH', 'EN goal': 'EN' }[s] || '')
const nhlPeriod = (p) => (/^\d/.test(p) ? `P${parseInt(p, 10)}` : p)
export const nhl = {
  /** nhlgoal / nhlcalled, NOT CALLED: ON THE BOARD / NOT ON THE BOARD / unlocked. */
  goal: ({ name, status, rank, strength, period, score }) => ({
    title: titleWith('\u{1F6A8}', name, 'scores'),
    body: fitBody([status === 'board' ? `${STATUS_WORD.board}${rank ? ` #${rank}` : ''}` : status === 'off' ? STATUS_WORD.off : '', nhlStrength(strength), nhlPeriod(period), score]),
    short: lastNameOf(name), group: 'scored',
  }),
  /** A CALLED goal keeps its words character for character (Donovan 2026-10-09); exempt from the length limits. */
  goalCalled: ({ last, strength, period, seasonGoals, nth }) => ({
    title: `\u{1F6A8} ${last.toUpperCase()} SCORES`,
    body: ['CALLED · the top skater on his team on the LAMP board',
      [strength, period, seasonGoals ? `his ${ord(Number(seasonGoals))}` : null, nth > 1 ? `${ord(nth)} tonight` : null].filter(Boolean).join(' · ')].filter(Boolean).join('\n'),
    short: `${last}${nth > 1 ? ` (${nth})` : ''}`, group: 'scored',
  }),
}

// ── PHONE PUSH: BUCKETS (off until BUCKETS opens) ───────────────────────────
export const nba = {
  thirty: ({ name, points, team, opp, status }) => ({
    title: titleWith('\u{1F3C0}', name, 'hits 30'),
    body: fitBody([statusBy(status), `${points} points`, `${team} vs ${opp}`]),
    short: lastNameOf(name), group: 'dropped 30',
  }),
  /** The X / Discord line for a 30-point night (lib/nba/moments.js). No link. */
  moment: ({ name, team, opp, called, rank }) => (called
    ? `\u{1F916} CALLED IT\n\n\u{1F3C0} ${String(name).toUpperCase()} DROPS A 30 PIECE\n${team} vs ${opp} · called before tip on the BUCKETS points board`
    : `\u{1F3C0} ${String(name).toUpperCase()} DROPS A 30 PIECE${rank ? ` · #${rank} on the board` : ''}\n${team} vs ${opp}`),
}

// ── BUNDLES AND SYSTEM PUSH ────────────────────────────────────────────────
/** Several events in one minute -> one notification. No "DASH" filler. */
export const bundleTitle = (sport, n, verb) => clip(`${EMOJI[sport] || EMOJI.mlb} ${n} ${verb || 'updates'}`, LIMITS.title)
export function bundleBody(parts, cap = 3) {
  const shown = parts.slice(0, cap)
  const more = parts.length - shown.length
  return clip(shown.join(SEP) + (more > 0 ? `${SEP}+${more}` : ''), LIMITS.body)
}
export const WELCOME = {
  title: '\u{1F514} Alerts are on',
  body: 'You will hear when a player you follow scores.',
}

// ── BELL, PROMPTS, TOASTS ───────────────────────────────────────────────────
export const bell = {
  // HONEST (2026-10-09): the page polls only while the tab is visible, so a
  // hidden tab banner cannot exist. Homers and "up now" also show as a banner
  // while the tab is open; everything else is on the page only; with the site
  // closed, only the phone push (sign-in needed) reaches you.
  armed: 'Alerts are on. While this tab is open, homers and “up now” also pop up as banners; the rest show on the page. Pick them in Alerts.',
  iosInstall: 'On iPhone, alerts only work once the site is on your Home Screen. Tap Share, then Add to Home Screen, and open it from there.',
  signIn: 'Alerts are on while the site is open. Sign in to get them with the site closed too.',
  denied: 'Notifications were not allowed.',
}
/** The iPhone hint, also used by the settings panel. */
export const installHintText = () => bell.iosInstall

export const toast = {
  homer: ({ name, n, role, score }) => `${name} goes deep${n > 1 ? ` (${n} tonight)` : ''}${role ? ` · ${role} pick` : ''}${score ? ` · ${score}` : ''}`,
  triple: ({ name, role, cleared }) => `${name} triples${cleared ? ` · ${role} bar cleared` : ''}`,
  double: ({ name, role, cleared, tb }) => `${name} doubles${cleared ? ` · ${role} bar cleared` : ` · ${tb} total bases`}`,
  barCleared: ({ name, role, h, ab, tb, score }) => `${name} clears the ${role} bar (${h}-for-${ab}${tb > 1 ? `, ${tb} total bases` : ''})${score ? ` · ${score}` : ''}`,
  strikeouts: ({ name, role, ab, k }) => `${name} (${role} pick) is 0-for-${ab} with ${plural(k, 'strikeout')}`,
  bigBases: ({ name, tb, h, ab }) => `${name} has ${tb} total bases (${h}-for-${ab})`,
  anyHomer: ({ name, n }) => `${name} goes deep${n > 1 ? ` (${n} tonight)` : ''}`,
  upNow: ({ name, who, arm, half, inning }) => `${name} is up now (${who})${arm ? ` vs ${arm}` : ''} · ${inningText(half, inning)}`,
  onDeck: ({ name, who }) => `${name} (${who}) is on deck`,
  notInLineup: ({ name, who, spot }) => `${name} (${who}) is not in tonight's lineup · MOONSHOT had him #${spot ?? '?'}`,
  newSlot: ({ name, who, slot, was }) => `${name} (${who}) is batting #${slot} tonight · MOONSHOT had #${was}`,
  nflKick: ({ away, home, name }) => `${away} at ${home} is under way — ${name} is on your list`,
  nflScores: ({ name, tds }) => `${name} scores${tds > 1 ? ` — touchdown #${tds}` : ''}`,
  nflBar: ({ name, market, now, bar }) => `${name} clears ${String(market).replace('_', ' ').toLowerCase()} — ${now} (bar ${bar})`,
}

export const livewire = {
  pairCashed: ({ a, b, label }) => `PAIR CASHED — ${a} and ${b} both went deep (${label})`,
  pairOneAway: ({ done, needs, label }) => `${done} went deep — ${needs} completes the “${label}” pair, game live`,
  poolCashed: ({ label, total }) => `POOL CASHED — ${label}, all ${total} went deep`,
  poolOneAway: ({ label, hit, total, missing }) => `${label} is ${hit}/${total} — one swing from cashing (${missing.join(', ')})`,
  stopped: ({ away, home, kind, reason, waiting }) => {
    const head = gameOffHeadline(kind, reason)
    const tail = kind === 'postponed' ? 'no at-bats will be played; those picks are void, not losses'
      : kind === 'suspended' ? 'it resumes later, so nothing is decided yet'
        : 'picks stay open until it resumes or the game ends'
    return `${away} at ${home}: ${head}${waiting ? ` (${plural(waiting, 'pick')} waiting)` : ''} — ${tail}`
  },
  stillNeeds: ({ name, role, need, inning }) => `${name} (${role} pick) still needs ${need} — ${ord(inning)} inning`,
  gassedPen: ({ name, pitches, penPitches, arms }) => `${name} is at ${pitches} pitches and his bullpen threw ${penPitches} yesterday (${plural(arms, 'arm')}) — tired relievers are the home run window`,
  penDoor: ({ name, pitches }) => `${name} is at ${pitches} pitches — bullpen door opening`,
  multiHr: ({ name, n, live }) => `${name} has ${n} home runs tonight${live ? ' — still batting' : ''}`,
}

// ── SETTINGS PANEL (lib/dash/alerts.js) ─────────────────────────────────────
// label + one-line detail per category key. Moved here so the panel and the
// push say the same thing.
export const CATEGORY_COPY = {
  homer: ['Homers', 'A followed hitter goes deep'],
  lineup: ['Lineup posted', 'He is in tonight, and where he is batting'],
  callup: ['Call-up', 'First time we have seen him in a posted lineup'],
  dropout: ['Lineup change', 'He is not in tonight’s lineup'],
  ondeck: ['On deck', 'He is up next. Says so when the bases are loaded.'],
  clutch: ['Clutch spot', 'At the plate late, runners on, game in the balance'],
  multihit: ['Multi-hit', 'Two hits, and again at three'],
  xbh: ['Extra-base hit', 'He doubles or triples'],
  hrr: ['HRR cleared', 'Hits + runs + RBI reaches two'],
  bigbases: ['Big bases', 'Four or more total bases'],
  cold: ['Going cold', '0-for with the strikeouts piling up'],
  firstpitch: ['First pitch', 'A game with one of your names starts'],
  finalline: ['Final line', 'His night is over, here is the line'],
  slate: ['Any slate homer', 'Anyone goes deep, with where he sat on the board'],
  atbat: ['At the plate', 'Your pick is batting right now'],
  cleared: ['Bar cleared', 'A MOONSHOT pick clears its own category bar'],
  boardup: ['Board set', 'Your picks are in the posted lineups'],
  lastcall: ['First pitch soon', 'Half an hour before a game with your picks in it'],
  gameoff: ['Delay or postponement', 'Rain delay, suspension or postponement'],
  scratched: ['Scratch', 'A board hitter who is out of the posted lineup'],
  slam: ['Bases loaded, he is up', 'Your hitter at the plate with the bases full'],
  leadchg: ['iLive', '7th on, within three runs, in a game you have somebody in'],
  gamefinal: ['Final score', 'How the game ended, once per game you had somebody in'],
  nfltd: ['Touchdowns', 'A followed player scores or throws a touchdown'],
  nflred: ['His offence is in the red zone', 'Your man’s team has the ball inside the twenty'],
  nflbig: ['Big day', '100 rushing or receiving, 300 passing'],
  nflclose: ['Close game', 'One score in the fourth, with your name in it'],
  nflkick: ['Kickoff', 'A game with one of your names starts'],
  nflbar: ['Market bar', 'He crosses the bar on one of the seven markets'],
  nhlgoal: ['Goals', 'A followed skater scores, and where he sat on the LAMP board'],
  nhlcalled: ['Any CALLED goal', 'Any skater the LAMP board called scores'],
}

// ── THE CUT (Donovan, 2026-10-09) ───────────────────────────────────────────
// ~12 phone categories that matter. The rest are OFF everywhere (the producer
// still builds them, wants() refuses them) and come back with the flag
// PUSH_CUT_CATEGORIES=on (Vercel env). Franchise (fr*) is owned by the
// FRANCHISE workflow and is not touched. "weekly" (the weekly recap) has no
// producer yet; it is listed so it is not forgotten.
//
// 21-day dash_push_log counts come from the 10-09 preview (rows = sent / bundled /
// dropped / failed). ONLY 3 devices exist; read the numbers as direction, not scale.
//
// category    keep|cut  21-day rows            why
export const PUSH_PLAN = {
  boardup:     { keep: true,  rows: '18 = 11 sent, 4 bundled, 0 dropped, 3 failed', why: 'Pregame, once a night, brings people to the board. Now waits for the lineup.' },
  lastcall:    { keep: true,  rows: '16 = 14 sent, 0 bundled, 0 dropped, 2 failed', why: 'Highest delivery rate of any category. Now once per start time, lineup-gated.' },
  scratched:   { keep: true,  rows: '57 = 16 sent, 9 bundled, 0 dropped, 32 failed', why: 'The alert you can still act on. Failures were one dead device.' },
  dropout:     { keep: true,  rows: '76 = 18 sent, 20 bundled, 0 dropped, 38 failed', why: 'Lineup change for followed men who are not on the board.' },
  gameoff:     { keep: true,  rows: '9 = 4 sent, 0 bundled, 0 dropped, 5 failed', why: 'Rare and nobody forgives missing it.' },
  homer:       { keep: true,  rows: '38 = 16 sent, 0 bundled, 0 dropped, 22 failed', why: 'The reason to follow a hitter. CALLED ones say so.' },
  nhlgoal:     { keep: true,  rows: '0 rows (no LAMP goal has reached a phone yet)', why: 'LAMP twin of homer. NO EVIDENCE yet, kept on principle.' },
  nhlcalled:   { keep: true,  rows: '0 rows (off by default)', why: 'The CALLED goal for anyone. Stays OFF by default.' },
  nfltd:       { keep: true,  rows: '2 = 0 sent, 0 bundled, 0 dropped, 2 failed', why: 'The touchdown. Now also counts a followed QB’s passing TD.' },
  nflkick:     { keep: true,  rows: '10 = 7 sent, 0 bundled, 0 dropped, 3 failed', why: 'Kickoff for a game with your names.' },
  finalline:   { keep: true,  rows: '201 = 1 sent, 31 bundled, 165 dropped, 4 failed', why: 'The final recap. 165 of 201 were eaten by the 30-minute lane, so it is now never dropped.' },
  weekly:      { keep: true,  rows: 'not built', why: 'Donovan listed a weekly recap; no producer exists. TODO.' },
  lineup:      { keep: false, rows: '257 = 25 sent, 86 bundled, 104 dropped, 42 failed', why: 'Fires most nights for a regular; lineup change covers the news.' },
  callup:      { keep: false, rows: '13 = 0 sent, 2 bundled, 8 dropped, 3 failed', why: 'Never delivered.' },
  firstpitch:  { keep: false, rows: '96 = 30 sent, 0 bundled, 58 dropped, 8 failed', why: 'Duplicates first pitch soon and the kickoff.' },
  multihit:    { keep: true , rows: '69 = 5 sent, 8 bundled, 52 dropped, 4 failed', why: 'Cash event (hit bar), kept (Donovan 10-09).' },
  xbh:         { keep: false, rows: '44 = 5 sent, 8 bundled, 27 dropped, 4 failed', why: 'Scoreboard noise.' },
  hrr:         { keep: true , rows: '103 = 14 sent, 8 bundled, 67 dropped, 14 failed', why: 'Cash event, kept (Donovan 10-09). Now never dropped by the lane windows.' },
  bigbases:    { keep: true , rows: '11 = 0 sent, 4 bundled, 7 dropped, 0 failed', why: 'Cash event (total bases), kept (Donovan 10-09).' },
  cold:        { keep: false, rows: '39 = 14 sent, 0 bundled, 21 dropped, 4 failed', why: 'Bad news nobody asked for.' },
  ondeck:      { keep: false, rows: '1192 = 309 sent, 18 bundled, 735 dropped, 130 failed', why: 'CUT completely (Donovan 10-09): two per plate appearance, 62% dropped. Merged into the bases-loaded alert.' },
  clutch:      { keep: false, rows: '81 = 8 sent, 1 bundled, 64 dropped, 8 failed', why: 'Mostly dropped.' },
  slam:        { keep: true , rows: '32 = 16 sent, 0 bundled, 0 dropped, 16 failed', why: 'Merged with ON DECK (Donovan 10-09): one alert when a pick is up with the bases loaded.' },
  leadchg:     { keep: false, rows: '80 = 8 sent, 3 bundled, 57 dropped, 12 failed', why: 'Scoreboard noise.' },
  gamefinal:   { keep: false, rows: '69 = 0 sent, 14 bundled, 54 dropped, 1 failed', why: 'Never delivered alone; final line is the recap.' },
  slate:       { keep: false, rows: '125 = 48 sent, 1 bundled, 76 dropped, 0 failed', why: 'About names you did not follow.' },
  nflred:      { keep: false, rows: '26 = 18 sent, 0 bundled, 0 dropped, 8 failed', why: 'Not on Donovan’s list. Delivered fine; one switch away.' },
  nflboardred: { keep: false, rows: 'not logged (off for phones)', why: 'A channel story, not a phone one.' },
  nflclose:    { keep: false, rows: '7 = 4 sent, 0 bundled, 2 dropped, 1 failed', why: 'Not on the list.' },
  nflbig:      { keep: false, rows: '3 = 2 sent, 0 bundled, 1 dropped, 0 failed', why: 'Not on the list.' },
  nba30:       { keep: false, rows: '0 rows (BUCKETS not public)', why: 'Off until BUCKETS opens.' },
  nbacalled:   { keep: false, rows: '0 rows (BUCKETS not public)', why: 'Off until BUCKETS opens.' },
}
const WEEKLY_ONLY = new Set(['weekly'])
export const KEPT_PUSH_CATEGORIES = new Set(Object.entries(PUSH_PLAN).filter(([k, v]) => v.keep && !WEEKLY_ONLY.has(k)).map(([k]) => k))
export const CUT_PUSH_CATEGORIES = new Set(Object.entries(PUSH_PLAN).filter(([, v]) => !v.keep).map(([k]) => k))
/** Is this category allowed to reach a phone? fr* (FRANCHISE) is never touched here. */
export function categoryAllowed(cat, env = (typeof process !== 'undefined' ? process.env : {})) {
  const c = String(cat || '')
  if (c.startsWith('fr')) return true
  if (!CUT_PUSH_CATEGORIES.has(c)) return true
  return String(env?.PUSH_CUT_CATEGORIES || '').toLowerCase() === 'on'
}

// ── THE CATALOG ─────────────────────────────────────────────────────────────
// Every message, with sample data (TEST data: invented players "Sample ...",
// clubs TST / EXA). scripts/build-notifications-preview.mjs renders this;
// scripts/check-notification-copy.mjs lints it. `kind`: push | toast | bell |
// livewire | system | post. `limits: false` exempts a row from the phone-length
// lint (page-only text).
const SG = { away: 'TST', home: 'EXA', awayScore: 2, homeScore: 3, half: 'Bottom', inning: 7 }
const L = { h: 2, ab: 3, tb: 5, r: 1, rbi: 1 }
const NG = { away: 'TST', home: 'EXA', away_score: 17, home_score: 20, period: 3 }
const GOAL = { name: 'Sample Alpha', strength: 'PP goal', period: '2nd', seasonGoals: 12, nth: 1, score: 'TST 3, EXA 2' }

export const CATALOG = [
  { key: 'boardup', sport: 'mlb', kind: 'push', trigger: 'The first lineup with a pick in it is posted (once a day).', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.boardSet({ count: 3, time: '7:05 PM ET' }) },
  { key: 'boardup', sport: 'mlb', kind: 'push', variant: 'one pick', trigger: 'Same, one pick.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.boardSet({ count: 1, time: '7:05 PM ET' }) },
  { key: 'lastcall', sport: 'mlb', kind: 'push', trigger: 'A game with your picks in the posted lineup starts within 30 minutes (once per start time).', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.firstPitchSoon({ mins: 30, count: 3 }) },
  { key: 'lastcall', sport: 'mlb', kind: 'push', variant: 'one pick', trigger: 'Same, one pick.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.firstPitchSoon({ mins: 25, count: 1 }) },
  { key: 'scratched', sport: 'mlb', kind: 'push', noStat: true, trigger: 'A board pick is not in a posted lineup.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.scratch({ name: 'Sample Delta' }) },
  { key: 'dropout', sport: 'mlb', kind: 'push', noStat: true, trigger: 'A followed man (not on the board) is left out of a posted lineup.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.lineupChange({ name: 'Sample Delta' }) },
  { key: 'gameoff', sport: 'mlb', kind: 'push', variant: 'rain delay, lineup posted', trigger: 'A game with your picks is delayed.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.gameOff({ kind: 'delayed', reason: 'Delayed: RAIN', away: 'TST', home: 'EXA', count: 2, lineupPosted: true }) },
  { key: 'gameoff', sport: 'mlb', kind: 'push', variant: 'delay, no lineup yet', trigger: 'Same, lineups not posted.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.gameOff({ kind: 'delayed', reason: 'Delayed Start: Rain', away: 'TST', home: 'EXA', count: 0, lineupPosted: false }) },
  { key: 'gameoff', sport: 'mlb', kind: 'push', variant: 'postponed', trigger: 'Postponed.', producer: 'lib/dash/pushRules.js pregameEventsFrom', render: () => mlb.gameOff({ kind: 'postponed', reason: 'Postponed (rain)', away: 'TST', home: 'EXA', count: 2, lineupPosted: false }) },
  { key: 'homer', sport: 'mlb', kind: 'push', variant: 'CALLED', trigger: 'A followed hitter goes deep; he was CALLED.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.homer({ name: 'Sample Alpha', n: 1, line: L, game: SG, called: true }) },
  { key: 'homer', sport: 'mlb', kind: 'push', variant: 'second homer', trigger: 'His second homer tonight.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.homer({ name: 'Sample Alpha', n: 2, line: { ...L, tb: 8 }, game: SG, called: false }) },
  { key: 'finalline', sport: 'mlb', kind: 'push', trigger: 'His night is over and he had an at-bat.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.finalLine({ name: 'Sample Alpha', line: { h: 2, ab: 4 }, bars: ['multi-hit', 'HRR'], game: { away: 'TST', home: 'EXA', awayScore: 5, homeScore: 3 } }) },
  { key: 'nfltd', sport: 'nfl', kind: 'push', variant: 'rushing or receiving, CALLED', trigger: 'A followed player scores (rushing or receiving).', producer: 'lib/dash/pushRules.js nflEventsFrom', render: () => nfl.touchdown({ name: 'Sample Receiver', tds: 1, line: { receptions: 6, receiving_yards: 112 }, game: NG, called: true }) },
  { key: 'nfltd', sport: 'nfl', kind: 'push', variant: 'passing', trigger: 'A followed quarterback throws a touchdown.', producer: 'lib/dash/pushRules.js nflEventsFrom', render: () => nfl.passingTouchdown({ name: 'Sample Passer', tds: 2, line: { passing_yards: 212 }, game: NG }) },
  { key: 'nflkick', sport: 'nfl', kind: 'push', trigger: 'A game with your players kicks off.', producer: 'lib/dash/pushRules.js nflEventsFrom', render: () => nfl.kickoff({ away: 'TST', home: 'EXA', count: 2 }) },
  { key: 'nhlgoal', sport: 'nhl', kind: 'push', limits: false, variant: 'CALLED (existing words, kept character for character)', trigger: 'A followed skater scores; he was CALLED.', producer: 'lib/nhl/goalFeed.js pushText', render: () => nhl.goalCalled({ ...GOAL, last: 'Alpha' }) },
  { key: 'nhlgoal', sport: 'nhl', kind: 'push', variant: 'ON THE BOARD', trigger: 'Same, on the board.', producer: 'lib/nhl/goalFeed.js pushText', render: () => nhl.goal({ ...GOAL, status: 'board', rank: 7, strength: 'Even strength' }) },
  { key: 'nhlgoal', sport: 'nhl', kind: 'push', variant: 'NOT ON THE BOARD', trigger: 'Same, off the board.', producer: 'lib/nhl/goalFeed.js pushText', render: () => nhl.goal({ ...GOAL, status: 'off', period: 'OT', seasonGoals: 0 }) },
  { key: 'bundle', sport: 'mlb', kind: 'system', trigger: 'Several events for one device in one minute.', producer: 'app/api/dash/push/tick/route.js bundle', render: () => ({ title: bundleTitle('mlb', 3, 'went deep'), body: bundleBody(['Sample Alpha', 'Sample Bravo', 'Sample Charlie']) }) },
  { key: 'bundle', sport: 'mlb', kind: 'system', variant: 'seven', trigger: 'Seven at once.', producer: 'app/api/dash/push/tick/route.js bundle', render: () => ({ title: bundleTitle('mlb', 7, 'went deep'), body: bundleBody(['Sample Alpha', 'Sample Bravo', 'Sample Charlie', 'Sample Delta', 'Sample Echo', 'Sample Foxtrot', 'Sample Golf']) }) },
  { key: 'welcome', sport: 'all', kind: 'system', trigger: 'A new device turns alerts on.', producer: 'app/api/dash/push/subscribe/route.js', render: () => ({ ...WELCOME }) },
  { key: 'ondeck', sport: 'mlb', kind: 'push', cut: true, trigger: 'CUT. A followed hitter is on deck in a live game.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.onDeck({ name: 'Sample Alpha', outs: 1, on: 2, loaded: false, game: SG }) },
  { key: 'slam', sport: 'mlb', kind: 'push', trigger: 'A pick is up with the bases loaded (this replaced ON DECK).', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.basesLoaded({ name: 'Sample Bravo', outs: 1, game: { away: 'TB', home: 'NYY', awayScore: 4, homeScore: 7, half: 'Top', inning: 6 } }) },
  { key: 'hrr', sport: 'mlb', kind: 'push', trigger: 'Hits + runs + RBI reaches two (a cash event).', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.hrrCleared({ name: 'Sample Alpha', line: { h: 2, r: 1, rbi: 1 }, game: { ...SG, away: 'TB', home: 'NYY', awayScore: 4, homeScore: 2, inning: 7 } }) },
  { key: 'bigbases', sport: 'mlb', kind: 'push', trigger: 'Four or more total bases (a cash event).', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.bigBases({ name: 'Sample Alpha', tb: 4, line: { h: 2, ab: 3 }, game: SG }) },
  { key: 'multihit', sport: 'mlb', kind: 'push', trigger: 'Two hits, and again at three (a cash event).', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.multiHit({ name: 'Sample Alpha', h: 2, ab: 3, game: SG }) },
  { key: 'slate', sport: 'mlb', kind: 'push', cut: true, trigger: 'CUT. Anyone goes deep.', producer: 'lib/dash/pushRules.js mlbEventsFrom', render: () => mlb.slateHomer({ name: 'Sample Echo', n: 1, status: STATUS_WORD.called, rank: 1, line: { h: 1, ab: 3 } }) },
  { key: 'nflred', sport: 'nfl', kind: 'push', cut: true, trigger: 'CUT. His offence is inside the 20.', producer: 'lib/dash/pushRules.js nflEventsFrom', render: () => nfl.redZone({ team: 'TST', names: ['Sample Receiver', 'Sample Passer'], down: '2nd & 6', clock: '4:12', game: NG }) },
  { key: 'nba30', sport: 'nba', kind: 'push', cut: true, trigger: 'CUT (BUCKETS off). A followed player reaches 30.', producer: 'lib/dash/pushRules.js nbaEventsFrom', render: () => nba.thirty({ name: 'Sample Guard', points: 31, team: 'TST', opp: 'EXA', status: 'called' }) },
  { key: 'bucketsPost', sport: 'nba', kind: 'post', trigger: 'A 30-point night (X / Discord, BUCKETS off).', producer: 'lib/nba/moments.js momentText', render: () => ({ title: 'X / Discord post', body: nba.moment({ name: 'Sample Guard', team: 'TST', opp: 'EXA', called: true }) }), limits: false },
  { key: 'bell-armed', sport: 'mlb', kind: 'bell', trigger: 'The bell is turned on and the browser allows it.', producer: 'components/MiniWire.js toggleNotif', render: () => ({ title: 'On-page message', body: bell.armed }), limits: false },
  { key: 'bell-ios', sport: 'mlb', kind: 'bell', trigger: 'Bell tapped in Safari on an iPhone that has not installed the site.', producer: 'lib/notify.js installHint', render: () => ({ title: 'On-page message', body: bell.iosInstall }), limits: false },
  { key: 'bell-signin', sport: 'mlb', kind: 'bell', trigger: 'Bell turned on while signed out.', producer: 'components/MiniWire.js toggleNotif', render: () => ({ title: 'On-page message', body: bell.signIn }), limits: false },
  { key: 'toast-hr', sport: 'mlb', kind: 'toast', trigger: 'A pick or watchlist man homers (page open).', producer: 'components/MiniWire.js', render: () => ({ title: '\u{1F4A5}', body: toast.homer({ name: 'Sample Alpha', n: 1, role: 'TOP', score: 'TST 3, EXA 2' }) }), limits: false },
  { key: 'toast-up', sport: 'mlb', kind: 'toast', trigger: 'A pick is at the plate (page open).', producer: 'components/MiniWire.js', render: () => ({ title: '⚾', body: toast.upNow({ name: 'Sample Alpha', who: 'TOP pick', arm: 'Reliever', half: 'Bottom', inning: 7 }) }), limits: false },
  { key: 'toast-k', sport: 'mlb', kind: 'toast', trigger: 'A pick goes 0-for with a second strikeout.', producer: 'components/MiniWire.js', render: () => ({ title: '⚠️', body: toast.strikeouts({ name: 'Sample Alpha', role: 'HR', ab: 3, k: 2 }) }), limits: false },
  { key: 'toast-scr', sport: 'mlb', kind: 'toast', trigger: 'A pick is not in a posted lineup (page open).', producer: 'components/MiniWire.js', render: () => ({ title: '\u{1F6AB}', body: toast.notInLineup({ name: 'Sample Alpha', who: 'TOP pick', spot: 3 }) }), limits: false },
  { key: 'toast-nfltd', sport: 'nfl', kind: 'toast', trigger: 'A followed player scores (page open).', producer: 'components/nfl/NflWire.js', render: () => ({ title: '\u{1F3C8}', body: toast.nflScores({ name: 'Sample Receiver', tds: 2 }) }), limits: false },
  { key: 'lw-pair', sport: 'mlb', kind: 'livewire', trigger: 'Both legs of a pair homered.', producer: 'components/LiveWire.js', render: () => ({ title: 'LiveWire', body: livewire.pairCashed({ a: 'Sample Alpha', b: 'Sample Bravo', label: 'SAMPLE PAIR' }) }), limits: false },
  { key: 'lw-stopped', sport: 'mlb', kind: 'livewire', trigger: 'A game is delayed, suspended or postponed.', producer: 'components/LiveWire.js', render: () => ({ title: 'LiveWire', body: livewire.stopped({ away: 'TST', home: 'EXA', kind: 'delayed', reason: 'Delayed: RAIN', waiting: 2 }) }), limits: false },
  { key: 'lw-needs', sport: 'mlb', kind: 'livewire', trigger: 'A live pick still needs something in the 7th or later.', producer: 'components/LiveWire.js', render: () => ({ title: 'LiveWire', body: livewire.stillNeeds({ name: 'Sample Alpha', role: 'TOP', need: 'a homer', inning: 8 }) }), limits: false },
  { key: 'lw-bullpen', sport: 'mlb', kind: 'livewire', trigger: 'A starter is at 85+ pitches.', producer: 'components/LiveWire.js', render: () => ({ title: 'LiveWire', body: livewire.gassedPen({ name: 'Starter', pitches: 92, penPitches: 160, arms: 6 }) }), limits: false },
  { key: 'lw-hr2', sport: 'mlb', kind: 'livewire', trigger: 'A hitter has 2+ homers tonight.', producer: 'components/LiveWire.js', render: () => ({ title: 'LiveWire', body: livewire.multiHr({ name: 'Sample Alpha', n: 2, live: true }) }), limits: false },
]
