// 🏀 BUCKETS' dictionary -- what a column header means, in plain words. The
// binding DenseTable uses on every product (components/Explain.js: a column
// earns a ⓘ by having an entry for its key or label). Only NON-OBVIOUS
// headers; standard NBA language first.
export const NBA_GLOSSARY = {
  score: 'The model’s score for this market tonight, 0-100: where the player ranks among everyone playing, on the legs shown beside it. A score is a rank, not a probability.',
  status: 'CALLED is the one pick per team in a game (the game’s higher one TOP, the other BUCKET). ON THE BOARD is the top third of the night. The labels lock before tip and never change.',
  gp: 'Games played.',
  min: 'Minutes per game.',
  pts: 'Points per game.',
  reb: 'Rebounds per game.',
  ast: 'Assists per game.',
  '3pm': 'Three-pointers made per game.',
  ptsPg: 'Points per game, this season and last pooled by games played.',
  rebPg: 'Rebounds per game, pooled this season and last.',
  astPg: 'Assists per game, pooled this season and last.',
  minPg: 'Minutes per game, pooled this season and last.',
  fgaPg: 'Field-goal attempts per game — how often he shoots.',
  ftaPg: 'Free-throw attempts per game — how often he gets to the line.',
  tpmPg: 'Three-pointers made per game.',
  tpaPg: 'Three-point attempts per game.',
  tpPct: 'Three-point percentage: his own once he has 30 attempts on file, the league’s until then.',
  praPg: 'Points + rebounds + assists per game.',
  fgaShare: 'Shot share: his field-goal attempts as a share of his team’s. The first-basket lane leans on it.',
  ddRate: 'The share of his last games (up to 82, this season then last) with a double-double: ten or more in two of points, rebounds, assists, steals, blocks. Counted from his game log.',
  ddRecent: 'Double-doubles in his last ten games, as a share of the ten.',
  tdRate: 'The share of his last games (up to 82, this season then last) with a triple-double, counted from his game log.',
  oppPts: 'Points per game tonight’s opponent allows.',
  oppReb: 'Rebounds per game tonight’s opponent allows.',
  oppAst: 'Assists per game tonight’s opponent allows.',
  oppTpm: 'Three-pointers per game tonight’s opponent allows.',
  pct: 'Winning percentage.',
  gb: 'Games behind the conference leader.',
  strk: 'The current streak: W3 is three straight wins.',
  l10: 'The record over the last ten games.',
  diff: 'Point differential per game: points scored minus points allowed.',
  ppg: 'Points scored per game.',
  oppg: 'Points allowed per game.',
  oppFgPct: 'The field-goal percentage this defence allows: its opponents’ makes over attempts.',
  rk: 'Rank among the 30 clubs for this stat. 1 = gives up the most — the softest matchup for an attacker.',
  'fg%': 'Field-goal percentage: makes over attempts, twos and threes.',
  '3p%': 'Three-point percentage.',
}
