'use client'

import { useMemo, useState } from 'react'
import { C, NUM_FONT, gradeFor } from '../../../lib/nfl/theme'
import { useNflWatchlist } from '../../../lib/nfl/watchlist'

export default function Watchlist({ data, onPlayerClick }) {
  const { pins, toggle } = useNflWatchlist(data)
  const [gameId, setGameId] = useState('all')
  const byId = useMemo(() => Object.fromEntries((data?.players || []).map((player) => [String(player.player_id), player])), [data])
  const games = useMemo(() => (data?.games || []).filter((game) => pins.some((pin) => pin.game_id === game.game_id)), [data, pins])
  const rows = pins.map((pin) => ({ pin, player: byId[String(pin.player_id)] })).filter((row) => row.player && (gameId === 'all' || row.pin.game_id === gameId))

  return <div className="nfl-watch"><section className="nfl-watch-hero"><div><small>YOUR TUDDY BOARD</small><h1>Watchlist</h1><p>Save a player from any card, then work one game at a time. Pins are rebuilt from the fresh slate row, including the game id.</p></div><strong>{pins.length}<span>PINNED</span></strong></section>{pins.length > 0 && <div className="nfl-watch-games"><button className={gameId === 'all' ? 'active' : ''} onClick={() => setGameId('all')}>ALL · {pins.length}</button>{games.map((game) => { const count = pins.filter((pin) => pin.game_id === game.game_id).length; return <button key={game.game_id} className={gameId === game.game_id ? 'active' : ''} onClick={() => setGameId(game.game_id)}>{game.away} @ {game.home} · {count}</button>})}</div>}<section className="nfl-watch-grid">{rows.map(({ pin, player }) => { const markets = Object.entries(player.scores || {}).filter(([, score]) => Number.isFinite(score)).sort((a, b) => b[1] - a[1]); const [best, score] = markets[0] || []; const grade = gradeFor(score); return <article key={player.player_id}><div className="nfl-watch-top"><span>{player.team}</span><button onClick={() => toggle(player)} aria-label={`Remove ${player.name} from watchlist`}>★</button></div><button className="nfl-watch-player" onClick={() => onPlayerClick?.(player, best || 'TD')}><small>{player.position} · vs {player.opp}</small><h2>{player.name}</h2><div><strong style={{ color: grade.color }}>{Number.isFinite(score) ? Math.round(score) : '—'}</strong><span>{best || 'UNSCORED'} · {grade.label}</span></div></button><div className="nfl-watch-scores">{markets.slice(0, 4).map(([market, value]) => <button key={market} onClick={() => onPlayerClick?.(player, market)}><small>{market}</small><b>{Math.round(value)}</b></button>)}</div><footer>{pin.away && pin.home ? `${pin.away} @ ${pin.home}` : 'GAME PENDING'}<span>{pin.kickoff ? new Date(pin.kickoff).toLocaleString('en-US', { weekday: 'short', hour: 'numeric', minute: '2-digit' }) : ''}</span></footer></article>})}{!rows.length && <div className="nfl-watch-empty"><span>☆</span><h2>{pins.length ? 'No pins in this game.' : 'Your watchlist is empty.'}</h2><p>Open any player card and tap SAVE TO WATCHLIST. The player will stay attached to this slate and game.</p></div>}</section><style>{`
    .nfl-watch{display:flex;flex-direction:column;gap:11px}.nfl-watch-hero{display:flex;align-items:center;justify-content:space-between;min-height:170px;padding:25px;border:1px solid rgba(34,211,238,.28);border-radius:16px;background:radial-gradient(circle at 85% 10%,rgba(34,211,238,.15),transparent 35%),radial-gradient(circle at 8% 100%,rgba(34,197,94,.12),transparent 38%),${C.bg2}}.nfl-watch-hero small{color:${C.cyan};font:900 8px/1 ${NUM_FONT};letter-spacing:.12em}.nfl-watch-hero h1{margin:7px 0 5px;font-size:clamp(32px,5vw,52px);letter-spacing:-.05em}.nfl-watch-hero p{max-width:650px;margin:0;color:${C.text3};font-size:10px;line-height:1.5}.nfl-watch-hero>strong{display:flex;flex-direction:column;align-items:center;color:${C.green};font:900 46px/1 ${NUM_FONT}}.nfl-watch-hero>strong span{margin-top:5px;color:${C.text3};font-size:8px}.nfl-watch-games{display:flex;gap:5px;overflow-x:auto}.nfl-watch-games button{flex:0 0 auto;padding:8px 11px;border:1px solid ${C.border};border-radius:8px;background:${C.bg2};color:${C.text3};font:800 8px/1 ${NUM_FONT};cursor:pointer}.nfl-watch-games button.active{border-color:${C.green};color:${C.green};background:rgba(34,197,94,.08)}.nfl-watch-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(270px,1fr));gap:9px}.nfl-watch-grid>article{overflow:hidden;border:1px solid ${C.border};border-radius:12px;background:${C.bg2}}.nfl-watch-top{display:flex;align-items:center;justify-content:space-between;padding:8px 10px;border-bottom:1px solid ${C.border}}.nfl-watch-top span{color:${C.green};font:900 9px/1 ${NUM_FONT}}.nfl-watch-top button{border:0;background:transparent;color:${C.yellow};font-size:15px;cursor:pointer}.nfl-watch-player{width:100%;padding:13px;border:0;background:transparent;color:inherit;text-align:left;cursor:pointer}.nfl-watch-player>small{color:${C.text3};font:800 8px/1 ${NUM_FONT}}.nfl-watch-player h2{margin:5px 0 10px;font-size:18px}.nfl-watch-player>div{display:flex;align-items:baseline;gap:7px}.nfl-watch-player strong{font:900 28px/1 ${NUM_FONT}}.nfl-watch-player span{color:${C.text3};font:800 8px/1 ${NUM_FONT}}.nfl-watch-scores{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid ${C.border}}.nfl-watch-scores button{min-height:49px;border:0;border-right:1px solid ${C.border};background:rgba(255,255,255,.02);color:inherit;cursor:pointer}.nfl-watch-scores small,.nfl-watch-scores b{display:block}.nfl-watch-scores small{color:${C.text3};font:700 7px/1 ${NUM_FONT}}.nfl-watch-scores b{margin-top:5px;font:900 11px/1 ${NUM_FONT}}.nfl-watch-grid footer{display:flex;justify-content:space-between;padding:8px 10px;color:${C.text3};font:700 8px/1 ${NUM_FONT};border-top:1px solid ${C.border}}.nfl-watch-empty{grid-column:1/-1;padding:45px 20px;border:1px dashed ${C.border2};border-radius:13px;text-align:center}.nfl-watch-empty span{color:${C.yellow};font-size:30px}.nfl-watch-empty h2{margin:8px 0 5px}.nfl-watch-empty p{margin:0;color:${C.text3};font-size:10px}
    @media(max-width:560px){.nfl-watch-hero{align-items:flex-start}.nfl-watch-hero>strong{font-size:32px}.nfl-watch-grid{grid-template-columns:1fr}}
  `}</style></div>
}
